// Generated by CoffeeScript 1.6.3
(function() {
  var define;

  if (typeof define === "undefined" || define === null) {
    define = require('amdefine')(module);
  }

  define([], function() {
    var call, create, exports, finalise;
    create = function() {
      var ctx;
      return ctx = {
        count: 0,
        results: []
      };
    };
    call = function(ctx) {
      var args, func, old_callback;
      func = arguments['1'];
      args = Array.prototype.slice.call(arguments, 2);
      old_callback = args[args.length - 1];
      if (typeof old_callback === 'function') {
        ctx.count++;
        args[args.length - 1] = function() {
          var args2;
          args2 = Array.prototype.slice.call(arguments);
          if (args2.length === 1) {
            ctx.results.push(args2[0]);
          }
          old_callback.apply(this, args2);
          ctx.count--;
          return finalise(ctx);
        };
        return func.apply(this, args);
      } else {
        ctx.count++;
        ctx.results.push(func.apply(this, args));
        ctx.count--;
        return finalise(ctx);
      }
    };
    finalise = function(ctx, f) {
      if (f != null) {
        ctx.f = f;
      }
      if (ctx.count === 0) {
        if (ctx.f != null) {
          return ctx.f(ctx.results);
        }
      }
    };
    return exports = {
      create: create,
      call: call,
      finalise: finalise
    };
  });

}).call(this);
